import { Platform } from 'react-native';
import notifee, { AndroidImportance, AndroidStyle } from '@notifee/react-native';
import { richMarkupToHtml, stripRichMarkup } from '@/src/utils/notificationFormat';

/** Same branding as the app launcher — used as the colored icon in the notification shade. */
const APP_ICON = require('../../assets/images/icon.png');

export const NOTIFEE_CHANNEL_ID = 'default';

/** Drawable generated by expo-notifications from adaptive-icon.png (matches launcher). */
const ANDROID_SMALL_ICON = 'notification_icon';

export async function ensureNotifeeChannel() {
  if (Platform.OS !== 'android') return;
  await notifee.createChannel({
    id: NOTIFEE_CHANNEL_ID,
    name: 'BiomicsHub Alerts',
    description: 'Course updates, live classes, and announcements',
    importance: AndroidImportance.HIGH,
    vibration: true,
    sound: 'default',
    visibility: 1
  });
}

/** Show a rich push on Android (HTML bold/color + poster thumbnail / big picture). */
export async function displayRichPush(data: Record<string, string | undefined>) {
  if (Platform.OS !== 'android') return;

  const title = String(data.title || 'BiomicsHub').trim();
  const messageRich = String(data.messageRich || data.message || '').trim();
  const imageUrl = String(data.imageUrl || '').trim();
  const htmlBody = String(data.messageHtml || richMarkupToHtml(messageRich) || stripRichMarkup(messageRich)).trim();

  await ensureNotifeeChannel();

  const android: NonNullable<Parameters<typeof notifee.displayNotification>[0]['android']> = {
    channelId: NOTIFEE_CHANNEL_ID,
    pressAction: { id: 'default' },
    smallIcon: ANDROID_SMALL_ICON,
    largeIcon: APP_ICON,
    color: '#3dd6c6',
    importance: AndroidImportance.HIGH
  };

  if (imageUrl) {
    android.style = {
      type: AndroidStyle.BIGPICTURE,
      picture: imageUrl,
      title,
      text: htmlBody || stripRichMarkup(messageRich)
    };
  } else if (htmlBody.length > 0) {
    android.style = {
      type: AndroidStyle.BIGTEXT,
      text: htmlBody
    };
  }

  await notifee.displayNotification({
    title,
    body: htmlBody || stripRichMarkup(messageRich),
    android,
    data: Object.fromEntries(Object.entries(data).map(([k, v]) => [k, String(v ?? '')]))
  });
}
