import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system';
import notifee, { AndroidImportance, AndroidStyle, AndroidVisibility } from '@notifee/react-native';
import { resolveApiAssetUrl } from '@/src/api/client';
import { richMarkupToHtml, stripRichMarkup } from '@/src/utils/notificationFormat';

/** Same branding as the app launcher — used as the colored icon in the notification shade. */
const APP_ICON = require('../../assets/images/icon.png');

export const NOTIFEE_CHANNEL_ID = 'biomicshub_alerts_v2';

/** Drawable generated by expo-notifications from adaptive-icon.png (matches launcher). */
const ANDROID_SMALL_ICON = 'notification_icon';

export async function ensureNotifeeChannel() {
  if (Platform.OS !== 'android') return;
  await notifee.createChannel({
    id: NOTIFEE_CHANNEL_ID,
    name: 'BiomicsHub Alerts',
    description: 'Course updates, live classes, and announcements',
    importance: AndroidImportance.HIGH,
    vibration: true,
    sound: 'default',
    visibility: AndroidVisibility.PUBLIC
  });
}

async function resolvePosterUri(imageUrl: string) {
  const resolved = resolveApiAssetUrl(imageUrl);
  if (!resolved || !/^https?:\/\//i.test(resolved)) return resolved;
  try {
    const ext = resolved.toLowerCase().includes('.png') ? '.png' : '.jpg';
    const dest = `${FileSystem.cacheDirectory ?? ''}push-poster-${Date.now()}${ext}`;
    const downloaded = await FileSystem.downloadAsync(resolved, dest);
    return downloaded.uri || resolved;
  } catch {
    return resolved;
  }
}

/** Show a rich push on Android (HTML bold/color + poster thumbnail / big picture). */
export async function displayRichPush(data: Record<string, string | undefined>) {
  if (Platform.OS !== 'android') return;

  const title = String(data.title || 'BiomicsHub').trim();
  const messageRich = String(data.messageRich || data.message || '').trim();
  const plainBody = stripRichMarkup(messageRich) || String(data.message || '').trim();
  const htmlBody = String(data.messageHtml || richMarkupToHtml(messageRich) || plainBody).trim();
  const imageUrl = resolveApiAssetUrl(String(data.imageUrl || '').trim());

  await ensureNotifeeChannel();

  const android: NonNullable<Parameters<typeof notifee.displayNotification>[0]['android']> = {
    channelId: NOTIFEE_CHANNEL_ID,
    pressAction: { id: 'default', launchActivity: 'default' },
    smallIcon: ANDROID_SMALL_ICON,
    largeIcon: imageUrl || APP_ICON,
    color: '#3dd6c6',
    importance: AndroidImportance.HIGH,
    visibility: AndroidVisibility.PUBLIC,
    showTimestamp: true,
    actions: [
      {
        title: 'Open',
        pressAction: { id: 'default', launchActivity: 'default' }
      }
    ]
  };

  if (imageUrl) {
    const posterUri = await resolvePosterUri(imageUrl);
    android.style = {
      type: AndroidStyle.BIGPICTURE,
      picture: posterUri,
      title,
      summary: plainBody,
      largeIcon: null
    };
  } else if (htmlBody.length > plainBody.length) {
    android.style = {
      type: AndroidStyle.BIGTEXT,
      text: htmlBody
    };
  }

  await notifee.displayNotification({
    title,
    subtitle: 'BiomicsHub',
    body: imageUrl ? plainBody : (htmlBody || plainBody),
    android,
    data: Object.fromEntries(Object.entries(data).map(([k, v]) => [k, String(v ?? '')]))
  });
}
